In [5]:
import numpy as np
import cv2

In [7]:
img=cv2.imread(r"C:\Users\ADMIN\Downloads\parrot 1.jpg")

In [9]:
img.shape           # actualyy image has (w,h) but when you convert into array it will change (h,w means rows=height and columns= width

(275, 183, 3)

# **1. Transilation**

In [15]:
tx=0
ty=0
t_m=np.array([[1,0,tx],[0,1,ty]],dtype=np.float32)

t_img=cv2.warpAffine(img,t_m,(183,275))

In [17]:
t_m

array([[1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [19]:
t_img.shape

(275, 183, 3)

In [21]:
cv2.imshow("o_i",img)
cv2.imshow("t_i",t_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
tx=50
ty=50
t_m=np.array([[1,0,tx],[0,1,ty]],dtype=np.float32)

t_img=cv2.warpAffine(img,t_m,(183,275),borderMode=cv2.BORDER_REFLECT)
t_img1=cv2.warpAffine(img,t_m,(183,275),borderMode=cv2.BORDER_CONSTANT,borderValue=(0,0,255))

In [25]:
cv2.imshow("o_i",img)
cv2.imshow("t_i",t_img)
cv2.imshow("t_i1",t_img1)
cv2.waitKey()
cv2.destroyAllWindows()

# **2. Rotation**

In [28]:
r_m=cv2.getRotationMatrix2D((137,91),-90,1)

In [30]:
r_m

array([[ 6.123234e-17, -1.000000e+00,  2.280000e+02],
       [ 1.000000e+00,  6.123234e-17, -4.600000e+01]])

In [32]:
r_img=cv2.warpAffine(img,r_m,(183,275))

In [34]:
cv2.imshow("o_i",img)
cv2.imshow("r_img",r_img)

cv2.waitKey()
cv2.destroyAllWindows()

In [36]:
r_img1=cv2.warpAffine(img,r_m,(183,275),borderMode=cv2.BORDER_REFLECT)

In [38]:
cv2.imshow("o_i",img)
cv2.imshow("r_img",r_img)
cv2.imshow("re_img",r_img1)
cv2.waitKey()
cv2.destroyAllWindows()

In [40]:
r_m=cv2.getRotationMatrix2D((0,0),10,1)
r_img1=cv2.warpAffine(img,r_m,(183,275))
cv2.imshow("o_i",img)
cv2.imshow("r_img",r_img)
cv2.imshow("re_img",r_img1)
cv2.waitKey()
cv2.destroyAllWindows()

In [42]:
img1=cv2.rotate(img,cv2.ROTATE_180)
img2=cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
img3=cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2.imshow("o_i",img)
cv2.imshow("r_img1",img1)
cv2.imshow("r_img2",img2)
cv2.imshow("r_img3",img3)
cv2.waitKey()
cv2.destroyAllWindows()

# **3. Scaling**

In [45]:
sx=1
sy=1
tx=0
ty=0
sc_m=np.array([[sx,0,tx],[0,sy,ty]],dtype=np.float32)

In [47]:
sc_m

array([[1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [49]:
scal_img=cv2.warpAffine(img,sc_m,(183,275))

In [51]:
cv2.imshow("o_i",img)
cv2.imshow("s_im",scal_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [53]:
sx=0.3
sy=0.3
tx=1
ty=1
sc_m=np.array([[sx,0,tx],[0,sy,ty]],dtype=np.float32)

In [55]:
scal_img=cv2.warpAffine(img,sc_m,(183,275))
cv2.imshow("o_i",img)
cv2.imshow("s_im",scal_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [57]:
cv2.imshow("o_i",cv2.resize(img,(500,500)))
cv2.imshow("s_im",cv2.resize(img,(50,50)))
cv2.waitKey()
cv2.destroyAllWindows()                  # resize only do resize but wrapaffin do resize and translation

In [59]:
zo_o=cv2.pyrDown(img)
zo_i=cv2.pyrUp(img)

In [61]:
cv2.imshow("o_i",zo_o)
cv2.imshow("s_im",zo_i)
cv2.waitKey()
cv2.destroyAllWindows()

# **4. Sheering**

In [64]:
shx=1
shy=3
tx=0
ty=0
sh_m=np.array([[1,shx,tx],[shy,1,ty]],dtype=np.float32)

In [66]:
scal_img=cv2.warpAffine(img,sh_m,(183,275))
cv2.imshow("o_i",img)
cv2.imshow("s_im",scal_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [68]:
cr_img=img[10:90,15:100]

In [70]:
cv2.imshow("orginal_image",img)
cv2.imshow("cropping_img",cr_img)
cv2.waitKey()
cv2.destroyAllWindows()